### ISSUE TITLE
Documenting how external customers should set up storage for migration

### ISSUE THREAD

**Issue by marill** [documaster-cloud/client-documentation#1]
## Context 
In order to run a batch migration job for a customer (that wants to manage their own migration storage account in Azure) we need to provide documentation on how they should set up the storage (container) correctly. 

## Task definition
Write documentation containing information about how to set up the storage account with a blob container.

## Definition of done
- [ ]  The documentation is written and the customer can access it in a publically available repo (`client-documentation`)
- [ ]  The documentation is read and understood by one customer

## Demo
Show the documentation.

**Comment by mariahilmojensen** [comment]
Link to document: https://github.com/documaster-cloud/client-documentation/blob/main/Azure/storage-account.md
